network_configs:
    T: 100
    dt: 0.1
    max_in_degree: 25
    max_out_degree: 25
    alpha: -0.1
    theta_I0: 0.03
    r_I: 0.3
    r_L: 0.05
    mu_I: 0.05
    mu_L: 0.05
    beta: 0.2
    kappa: 1